# Generated by Django 3.0.7 on 2020-06-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_goal', models.CharField(choices=[('To have fun', 'To have fun'), ('To play competitively', 'To play competitively'), ('To become a pro', 'To become a pro')], max_length=100)),
                ('team_country', models.CharField(choices=[('Ukraine', 'Ukraine'), ('Russia', 'Russia'), ('Germany', 'Germany'), ('USA', 'USA'), ('Sweden', 'Sweden'), ('Poland', 'Poland'), ('Spain', 'Spain'), ('Serbia', 'Serbia'), ('France', 'France'), ('Belarus', 'Belarus')], max_length=100)),
                ('team_language', models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish'), ('Swedish', 'Swedish'), ('German', 'German'), ('French', 'French')], max_length=100)),
                ('team_region', models.CharField(choices=[('EU East', 'EU East'), ('EU West', 'EU West'), ('EU South', 'EU South'), ('America', 'America'), ('CIS', 'CIS'), ('India', 'India'), ('Oceania', 'Oceania')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_password', models.CharField(max_length=100)),
                ('player_email', models.CharField(max_length=100)),
                ('faceit_link', models.CharField(max_length=100)),
                ('steam_link', models.CharField(max_length=100)),
                ('player_country', models.CharField(choices=[('Ukraine', 'Ukraine'), ('Russia', 'Russia'), ('Germany', 'Germany'), ('USA', 'USA'), ('Sweden', 'Sweden'), ('Poland', 'Poland'), ('Spain', 'Spain'), ('Serbia', 'Serbia'), ('France', 'France'), ('Belarus', 'Belarus')], max_length=100)),
                ('player_region', models.CharField(choices=[('EU East', 'EU East'), ('EU West', 'EU West'), ('EU South', 'EU South'), ('America', 'America'), ('CIS', 'CIS'), ('India', 'India'), ('Oceania', 'Oceania')], max_length=100)),
                ('player_goal', models.CharField(choices=[('To have fun', 'To have fun'), ('To play competitively', 'To play competitively'), ('To become a pro', 'To become a pro')], max_length=100)),
                ('player_language', models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish'), ('Swedish', 'Swedish'), ('German', 'German'), ('French', 'French')], max_length=100)),
                ('player_skill', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=100)),
                ('player_rank', models.CharField(choices=[('Silver I', 'Silver I'), ('Silver II', 'Silver II'), ('Silver III', 'Silver III'), ('Silver IV', 'Silver IV'), ('Silver Elite', 'Silver Elite'), ('Silver Elite Master', 'Silver Elite Master'), ('Gold Nova I', 'Gold Nova I'), ('Gold Nova II', 'Gold Nova II'), ('Gold Nova III', 'Gold Nova III'), ('Gold Nova Master', 'Gold Nova Master'), ('Master Guardian I', 'Master Guardian I'), ('Master Guardian II', 'Master Guardian II'), ('Master Guardian Elite', 'Master Guardian Elite'), ('Distinguished Master Guardian', 'Distinguished Master Guardian'), ('Legendary Eagle', 'Legendary Eagle'), ('Legendary Eagle Master', 'Legendary Eagle Master'), ('Supreme Master First Class', 'Supreme Master First Class'), ('The Global Elite', 'The Global Elite')], max_length=100)),
                ('player_mainrole', models.CharField(choices=[('Assault', 'Assault'), ('Sniper', 'Sniper'), ('Support', 'Support')], max_length=100)),
                ('player_tacticalrole', models.CharField(choices=[('Captain', 'Captain'), ('Coach', 'Coach'), ('Strategist', 'Strategist')], max_length=100)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findert.Team')),
            ],
        ),
    ]
