# Generated by Django 3.0.7 on 2020-06-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_country',
            field=models.CharField(choices=[('Ukraine', 'Ukraine'), ('Russia', 'Russia'), ('USA', 'USA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_language',
            field=models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Ukrainian', 'Ukrainian')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_region',
            field=models.CharField(choices=[('EU East', 'EU East'), ('America', 'America'), ('CIS', 'CIS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findert.Team'),
        ),
    ]
